"""Nutrient migration

Revision ID: 67ffb459c66e
Revises: 
Create Date: 2023-10-31 17:43:09.941684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ffb459c66e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fiber', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vitamin_a', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('iron', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('zinc', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('carbohydrate', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('carbohydrate')
        batch_op.drop_column('zinc')
        batch_op.drop_column('iron')
        batch_op.drop_column('vitamin_a')
        batch_op.drop_column('fiber')
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('energy')

    # ### end Alembic commands ###
